  [build.environment]
REACT_APP_MEAL_RECIPE_API_KEY='3c50daaf95mshbd2a2526de893a8p15ec12jsn6b67b4cc36af'
REACT_APP_MEAL_RECIPE_API_HOST='food-recipe-api.p.rapidapi.com'

  [dev.environment]
REACT_APP_MEAL_RECIPE_API_KEY='3c50daaf95mshbd2a2526de893a8p15ec12jsn6b67b4cc36af'
REACT_APP_MEAL_RECIPE_API_HOST='food-recipe-api.p.rapidapi.com'

  [[redirects]]
  to="/"
  from="/*"
  status=200